
<?= $this->render('search_tpl.phtml') ?>
<a id="top"></a>
<div class="show_goods" id="show_goods"><div class="animate"></div></div>
<script type="tpl" id="tpl">    
    <div class="box" style="background-color: {{color}}">                    
        <div class="back" style="display:none;" title="{{name}}">
            <div>{{detail}}...</div>
            <div>标签：{{tags}}</div>
            <div class="bottom"id ="{{id}}">
                <a href="javascript:void(0);" class="{{like_class}} icon" title="I like it."></a>
                <div class="icon" title="I like it.">({{like_num}})</div>
                <a href="javascript:void(0);" class="hate icon" title="I hate it."></a>
                <div class="icon" title="I hate it.">({{hate_num}})</div>

                <a href="/sale/exchange/gid/{{id}}" class="exchange icon" title="交换"></a>
                <a href="/sale/sale/gid/{{id}}" class="sale icon" title="交易"></a>
                <a href="javascript:void(0);" class="detail icon" title="more detail"></a>
                <label style="display:none;">{{id}}</label>
                <div class="clear"></div>
            </div></div>
        <div class="front">
            <img src="/img/{{pic_id}}"/>
            <h3>{{name_cut}}</h3>
            <div>发布时间：{{publish_time}}</div>
            <div>过期时间：{{expire_date}}</div>
            <div>点击：{{click}}</div>          
        </div>
    </div>
</script>
<div class="goods_container" id="container">

</div>
<div id="page_loading">
    <span><img src="/img/loading.gif" />给力加载中……</span>
</div>

<script type="text/javascript">
    jQuery.extend(jQuery.easing, {
        easeInOutBack: function(e, f, a, i, h, g) {
            if (g == undefined) {
                g = 1.70158
            }
            if ((f /= h / 2) < 1) {
                return i / 2 * (f * f * (((g *= (1.525)) + 1) * f - g)) + a
            }
            return i / 2 * ((f -= 2) * f * (((g *= (1.525)) + 1) * f + g) + 2) + a
        }
    });
        
    $('#container').masonry({
        itemSelector : '.box',
        columnWidth: function( containerWidth ) {
            return containerWidth / 4;
        },
        isAnimated: true,
        animationOptions: {
            duration: 800,
            easing: 'easeInOutBack'
        }
    });
    var page = 1;
    var tpl = $("#tpl").html();
    function loadData(){       
        $.get("/goods/ajaxindex/page/" + page,null,function(data){
            if(data.length == 0){
                $("#page_loading span").text("木有了噢，最后一页了！");
                $("#page_loading").show("fast");
                setTimeout("$('#page_loading').hide()",2000);
                setTimeout("$('#page_loading').remove()",2100);
            }else{
                for(var key1 in data){
                    var tmp_data = tpl;
                    var tags_link = "";
                    for(var key3 in data[key1]['tags']){
                        tags_link += "<a href='/goods/search?q="+data[key1]['tags'][key3]+"'>"+data[key1]['tags'][key3]+" </a>";
                    }
                    tmp_data = tmp_data.replace("{{tags}}", tags_link)
                    tmp_data = tmp_data.replace("{{name_cut}}", data[key1]['name'].substring(0,20))
                    for(var key2 in data[key1]){
                        tmp_data = tmp_data.replace(new RegExp("{{"+key2 +"}}", "g"), data[key1][key2]);                       
                    }
                    var $tmp = $(tmp_data);
                    $("#container").append($tmp).masonry( 'appended', $tmp,false );
                }
                $("#page_loading").hide("fast");
            }
        },"json");
    }
    
    loadData();
    
    $(window).bind("scroll",function(){
        if( $(document).scrollTop() + $(window).height() > $(document).height() - 10 ) {
            $("#page_loading").show("slow");             
            page++;loadData();         
        }
    });

        
    $(".sale").fancybox({
        'type':'iframe',
        'height':800,
        'width':960
    });
    $(".exchange").fancybox({
        'type':'iframe',
        'height':800,
        'width':960
    });
    $('.box').live('mouseover',function(){
        $(this).find('.back').show();
        $(this).find('.front').hide();
    });
    $('.box').live('mouseleave',function(){
        $(this).find('.back').hide();
        $(this).find('.front').show();
    });
    $('.detail').live('click',function(){
        $.scrollTo($("#top"),800);
        pro = $('#show_goods');
        pro.css("background-color","red");
        pro.find(".animate").css("background-color","black");
        pro.find(".animate").animate({width:"960px"},500);
        id = $(this).parent().find("label").html();
        color = $(this).parent().parent().parent().css("background-color");
        pro.load("/goods/ajaxdetail/gid/" + id,null,function(){  
            pro.css("background-color",color);
            pro.animate({height:"700px"});
        });
    });
<?php if (isset($this->uid)): ?>
        $(".like").live('click',function(){
            t = $(this);
            id = $(this).parent().attr("id");
            $.get('/goods/like/gid/' + id,null,function(data){           
                if(data == 'success'){
                    t.removeClass("like");
                    t.addClass("like_red");
                }
            });
        });
        $(".like_red").live('click',function(){
            t = $(this);
            id = $(this).parent().attr("id");
            $.get('/goods/like/gid/' + id,null,function(data){
                if(data == 'success'){
                    t.removeClass("like_red");
                    t.addClass("like");
                }
            });
        });
        $(".hate").live('click',function(){
            t = $(this);
            id = $(this).parent().attr("id");
            $.get('/goods/hate/gid/' + id,null,function(data){
                t.parent().parent().parent().hide();
            });
        });
<?php endif; ?>
</script>