<h1>商品搜索：</h1>
<div class="search">
    <form method="get">
        <div>请输入关键字：</div>
        <div class="search_area">
            <input type="text" name="q"/>
            <br/>
            <input type="submit" name="submit" value="搜索" class="button"/></div>
    </form>
</div>
<div class="searchoutcome">
    <?php if ($this->count > 0): ?>
        <ul>
            <?php foreach ($this->paginator as $tmp): ?>
                <li><a href="<?= $tmp['url'] ?>" target="_blank"><?= $tmp['name'] ?></a></li>
            <?php endforeach; ?>	 
        </ul>
        <?= $this->paginationControl($this->paginator, 'Sliding', 'page_list.phtml'); ?>
    <?php else: ?>
        抱歉，没有搜索到相应结果！
    <?php endif; ?>
</div>