<h1>物品搜索：</h1>
<?= $this->render('search_tpl.phtml') ?>
<div class="searchoutcome">
    <?php if ($this->count > 0): ?>
        <ul>
            <?php foreach ($this->paginator as $tmp): ?>
                <li><a href="<?= $tmp['url'] ?>" target="_blank"><?= $tmp['name'] ?></a></li>
            <?php endforeach; ?>	 
        </ul>
        <?= $this->paginationControl($this->paginator, 'Sliding', 'page_list.phtml'); ?>
    <?php else: ?>
        抱歉，没有搜索到相应结果！
    <?php endif; ?>
</div>