<div id="welcome">
    <h1>主页</h1>
    <?php echo $this->infoNotify?>
    <p><?php echo $this->msg?></p>
    <div id="more-information">
        <p><?php echo $this->content;?></p>
    </div>
    <div><h2>交易信息：</h2><div><?php echo $this->sale_msg;?></div>
        <div><?php echo $this->sale_outcome_msg;?></div></div>
    <div>
        <a href="/user/reg">注册</a>
        <a href="/user/modify">更改个人资料</a>
    </div>
</div>