<?php if ($this->pageCount): ?> 
    <div class="pagination">
        <!-- First page link -->
        <ul>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $this->url(array('page' => $this->first)); ?>">
                        第一页
                    </a></li>
            <?php else: ?>
                <li><span class="disabled">第一页</span></li>
            <?php endif; ?>
            <!-- Previous page link --> 
            <?php if (isset($this->previous)): ?> 
                <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?> ">&lt;上一页</a></li>
            <?php else: ?> 
                <li><span class="disabled">&lt;上一页</span></li>
            <?php endif; ?> 

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?> 
                <?php if ($page != $this->current): ?>
                    <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li> 
                <?php else: ?>
                    <li><span class="disabled"><?= $page; ?></span></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link --> 
            <?php if (isset($this->next)): ?> 
                <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">下一页&gt;</a></li>
            <?php else: ?> 
                <li><span class="disabled">下一页&gt;</span></li>
            <?php endif; ?> 
            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url(array('page' => $this->last)); ?>">
                        最后一页
                    </a></li>
            <?php else: ?>
                <li><span class="disabled">最后一页</span></li>
            <?php endif; ?>
        </ul>
    </div> 
<div class="clear"></div>
<?php endif; ?>