<?php if ($this->pageCount): ?> 
    <ul class="pagination">
        <?php if (isset($this->previous)): ?><li><a href="<?= $this->url(array('page' => $this->previous)); ?>">&laquo;Previous</a></li>
        <?php else: ?><li class="previous-off">&laquo;Previous</li>
        <?php endif; ?>
        
        <?php foreach ($this->pagesInRange as $page): ?> 
                <?php if ($page != $this->current): ?>
                    <li><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li> 
                <?php else: ?>
                    <li class="active"><?= $page; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
                    
        <?php if (isset($this->next)): ?><li class="next"><a href="<?= $this->url(array('page' => $this->next)); ?>">Next &raquo;</a></li>
        <?php else: ?><li class="next-off">Next &raquo;</li>
        <?php endif; ?>
    </ul>
<?php endif; ?>