<h1>其他请求</h1>
<div>您同意的交易中的物品，共有<?=$this->other_req_num?>位用户请求</div>
<div><a href="/sale/request">返回</a></div>
<div>详细如下：</div>
<?php foreach ($this->paginator as $tmp): ?>
        <div class="sale_request">
            <div>买家: <a href='/user/profile?uid=<?= $tmp['sellerid'] ?>'><?= $tmp['name'] ?></a> 想以</div>
            <?php if ($tmp['use_goods'] == "money") : ?>
                <div class="use"><strong>交易</strong>方式购买您的</div>
            <?php else : ?>
                <div class="use"><ul><?php foreach ($tmp['use_names'] as $gid => $name) : ?>
                    <li><a href='/goods/detail?gid=<?= $gid ?>'><?= $name; ?></a></li>
                <?php endforeach; ?></ul>
                <strong>交换</strong>您的</div>
            <?php endif; ?>
                <div class="for"><ul><?php foreach ($tmp['ask_names'] as $gid => $name) : ?>
                <li><a href='/goods/detail?gid=<?= $gid ?>'><?= $name; ?></a></li>
            <?php endforeach; ?></ul></div>
            <a href='/sale/refuse?sid=<?= $tmp['sid'] ?>'>拒绝</a>
            <a href='/sale/accept?sid=<?= $tmp['sid'] ?>'>同意</a>
        </div>
    <?php endforeach; ?>
<?= $this->paginationControl($this->paginator, 'Sliding', 'page_list.phtml'); ?>