<h1>我的朋友</h1>
<div class="my_friend">
    <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $tmp): ?>
            <div><div><img src='<?= $tmp['small_avater'] ?>' alt='<?= $tmp['name'] ?>'/></div>
                <a href='/user/profile?uid=<?= $tmp['uid'] ?>'><?= $tmp['name'] ?></a>
                <div><a href='/msg/quickmsg?uid=<?= $tmp['uid'] ?>' class='msg'>给TA留言</a></div>
                <a href='/friends/delete?uid=<?= $tmp['uid'] ?>'>删除</a>
            </div>
        <?php endforeach; ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'page_list.phtml'); ?>
    <?php else: ?>
        "你还没有朋友哦，赶快去找找吧！
    <?php endif ?>
</div>
<script type="text/javascript">
    $(".msg").fancybox({
        'autoScale'			: true,
        'transitionIn'		: 'none',
        'transitionOut'		: 'none',
        'type'				: 'ajax'
    });
</script>