
<h1>用户登录</h1>
<?php echo $this->form; ?>
<form method="post" action="">
    <div class="zend_form">
        <div class="element"><div id="email-label"><label for="email" class="label required">邮箱:</label></div>
            <input type="text" name="email" id="email" value=""></div>
        <div class="element"><div id="password-label"><label for="password" class="label required">密码:</label></div>
            <input type="password" name="password" id="password" value=""></div>
        <div class="submit">
            <input type="submit" value="提交" class="button">
        </div></div>
</form>