<h1>邮箱激活</h1>
<div class="zend_form">
    <form method="post" action="">
        <div class="element"><label class="label required">邮箱:</label>
            <input type="text" name="email" id="email" value=""></div>
        <div class="code"><label class="label required">验证码:</label>
            <div class="img"><img src="/img/code"/></div><input type="text" name="code" id="code" value=""></div>
        <div class="clear"></div>
        <div class="submit">
            <input type="submit" value="提交" class="button">
        </div>
    </form></div>