<div id="main-wrapper">
    <div id="main-content">
        <div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all form-container">
            <div class="portlet-header ui-widget-header">物品列表</div>
            <div class="portlet-content">
                <div class="title">
                    <h3>物品列表</h3>
                </div>
                <div class="hastable">
                    <form name="myform" class="pager-form" method="post" action="">
                        <table> 
                            <thead> 
                                <tr>
                                    <th><input type="checkbox" value="check_none" onclick="this.value=check(this.form.list)" class="submit"/></th>
                                    <th>GID</th> 
                                    <th>价格</th>
                                    <th>交换条件</th>
                                    <th>名称</th>
                                    <th>细节</th> 
                                    <th>状态</th> 
                                    <th>发布时间</th>
                                    <th>卖家</th>
                                    <th>方式</th>
                                    <th>截止时间</th>
                                    <th style="width:132px">Options</th> 
                                </tr> 
                            </thead> 
                            <tbody>
                                <?php foreach ($this->paginator as $tmp): ?>
                                    <tr>
                                        <td class="center"><input type="checkbox" value="1" name="list" class="checkbox"/></td> 
                                        <td><?= $tmp['id'] ?></td> 
                                        <td><?= $tmp['price'] ?></td> 
                                        <td><?= $tmp['ex_cond'] ?></td> 
                                        <td><?= $tmp['name'] ?></td> 
                                        <td title="<?= $tmp['detail'] ?>" class="tooltip"><?= $tmp['detail_cut'] ?></td>
                                        <td><?= $tmp['status'] ?></td>
                                        <td><?= $tmp['publish_time'] ?></td>
                                        <td><a href="/profile/<?= $tmp['uid'] ?>" target="_blank" title="UID:<?= $tmp['uid'] ?>" class="tooltip"><?= $tmp['uname'] ?></td> 
                                        <td><?= $tmp['sale_ways'] ?></td>
                                        <td><?= $tmp['expire_date'] ?></td> 
                                        <td id="<?= $tmp['id'] ?>">
                                            <a class="btn_no_text btn ui-state-default ui-corner-all tooltip" title="Edit this goods" href="#">
                                                <span class="ui-icon ui-icon-wrench"></span>
                                            </a>
                                            <a class="btn_no_text btn ui-state-default ui-corner-all tooltip delete" title="Delete this goods" href="javascript:void(0);">
                                                <span class="ui-icon ui-icon-circle-close"></span>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                    <?= $this->paginationControl($this->paginator, 'Sliding', 'page_list_admin.phtml'); ?>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div id="delete-confirm" title="Delete this goods?">
        <div class="response-msg ui-corner-all" style="display:none;"></div>
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Goods will be deleted， Are you sure?</p>
    </div>
    <div class="clearfix"></div>
</div>

<script type="text/javascript">
    var cur_id;
    $( "#delete-confirm" ).dialog({
        autoOpen: false,
        resizable: false,
        modal: true,
        buttons: {
            "Delete this goods": function() {
                $.get("/admin/goodsdelete/gid/" + cur_id,null,function(data){
                    t = $("#delete-confirm").find(".response-msg");
                    if(data == "success"){   
                        t.html("<span>删除成功</span>");
                        t.removeClass("error");
                        t.addClass("success");
                        setTimeout( '$("#delete-confirm" ).dialog( "close" );',3000);
                    }else if(data == "fail"){
                        t.html("<span>删除失败</span>");
                        t.removeClass("success");
                        t.addClass("error");
                    }
                    t.show();
                });
                
            },
            "Cancel": function() {
                $( this ).dialog( "close" );
            }
        }
    });
    
    $(".delete").click(function(){
        cur_id= $(this).parent().attr("id");
        $( "#delete-confirm" ).dialog("open");
    });
</script>