<div id="main-wrapper">
    <div id="main-content">
        <div class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all form-container">
            <div class="portlet-header ui-widget-header">物品列表</div>
            <div class="portlet-content">
                <div class="title">
                    <h3>物品列表</h3>
                </div>
                <div class="hastable">
                    <form name="myform" class="pager-form" method="post" action="">
                        <table> 
                            <thead> 
                                <tr>
                                    <th><input type="checkbox" value="check_none" onclick="this.value=check(this.form.list)" class="submit"/></th>
                                    <th>GID</th> 
                                    <th>价格</th>
                                    <th>交换条件</th>
                                    <th>名称</th>
                                    <th>细节</th> 
                                    <th>状态</th> 
                                    <th>发布时间</th>
                                    <th>卖家</th>
                                    <th>方式</th>
                                    <th>截止时间</th>
                                    <th style="width:132px">Options</th> 
                                </tr> 
                            </thead> 
                            <tbody>
                                <?php foreach ($this->paginator as $tmp): ?>
                                    <tr>
                                        <td class="center"><input type="checkbox" value="1" name="list" class="checkbox"/></td> 
                                        <td><?= $tmp['id'] ?></td> 
                                        <td><?= $tmp['price'] ?></td> 
                                        <td><?= $tmp['ex_cond'] ?></td> 
                                        <td><?= $tmp['name'] ?></td> 
                                        <td><?= $tmp['detail'] ?></td>
                                        <td><?= $tmp['status'] ?></td>
                                        <td><?= $tmp['publish_time'] ?></td>
                                        <td><?= $tmp['uid'] ?></td> 
                                        <td><?= $tmp['sale_ways'] ?></td>
                                        <td><?= $tmp['expire_date'] ?></td> 
                                        <td>
                                            <a class="btn_no_text btn ui-state-default ui-corner-all tooltip" title="Edit this goods" href="#">
                                                <span class="ui-icon ui-icon-wrench"></span>
                                            </a>
                                            <a class="btn_no_text btn ui-state-default ui-corner-all tooltip" title="Delete this goods" href="#">
                                                <span class="ui-icon ui-icon-circle-close"></span>
                                            </a>
                                            <a class="btn_no_text btn ui-state-default ui-corner-all tooltip" title="Lock this user" href="#">
                                                <span class="ui-icon ui-icon-locked"></span>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>
                    <?= $this->paginationControl($this->paginator, 'Sliding', 'page_list_admin.phtml'); ?>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>